import axios from 'axios'

// ─── Qwa Class (self-contained) ───────────────────────────────────────────────
class Qwa {
  constructor() {
    this.url = 'https://qwa.eeq.my.id/api/generate'
  }

  _toBase64(v) {
    return Buffer.isBuffer(v)
      ? `data:image/png;base64,${v.toString('base64')}`
      : v || ''
  }

  async generate({ message, ...rest }) {
    try {
      const payload = {
        sender_name: rest?.sender_name || `User-${Math.floor(Math.random() * 1000)}`,
        message:     message || `Sent at ${new Date().toISOString()}`,
        ...(rest?.sender_number && { sender_number: rest.sender_number }),
        ...(rest?.sender_avatar && { sender_avatar: this._toBase64(rest.sender_avatar) }),
        ...(rest?.sender_image  && { sender_image:  this._toBase64(rest.sender_image)  }),
        ...(rest?.time          && { time:           rest.time                          }),
        ...(rest?.background !== undefined && { background: rest.background }),
        ...(rest?.quoted && {
          quoted: { ...rest.quoted, image: this._toBase64(rest.quoted?.image) },
        }),
      }

      const { data, headers } = await axios.post(this.url, payload, {
        responseType: 'arraybuffer',
        headers: { 'Content-Type': 'application/json' },
      })

      return {
        buffer:      Buffer.from(data),
        contentType: headers['content-type'] || 'image/png',
      }
    } catch (e) {
      const msg = e?.response?.data
        ? Buffer.from(e.response.data).toString()
        : e.message
      throw new Error(msg)
    }
  }
}

// ─── Handler ──────────────────────────────────────────────────────────────────
const handler = async (m, { conn, usedPrefix, command, args, quoted }) => {

  // ── Guide card (no args) ──────────────────────────────────────────────────
  if (!args[0]) {
    const guide = `
🖼️  *Fake WhatsApp Chat Generator*

Generate a realistic-looking WhatsApp chat screenshot with a custom sender name and message — great for fun, memes, or creative content!

━━━━━━━━━━━━━━━━━━━━
📌  *Basic usage:*
  ${usedPrefix}${command} <SenderName> | <message>

📌  *Examples:*
  ${usedPrefix}${command} Ahmed | Hello, how are you?
  ${usedPrefix}${command} Silana Bot | I'm an AI assistant 🤖
  ${usedPrefix}${command} Mom | Don't forget to eat lunch!

━━━━━━━━━━━━━━━━━━━━
📌  *Optional — reply to an image* to use it as the sender's avatar photo.

⚠️  *Notes:*
  • Sender name and message are separated by  |
  • Keep the message clean and reasonable in length
  • The image is generated by a third-party API
`.trim()

    return m.reply(guide)
  }

  // ── Parse input: "SenderName | message" ──────────────────────────────────
  const raw   = args.join(' ')
  const parts = raw.split('|').map(s => s.trim())

  if (parts.length < 2 || !parts[0] || !parts[1]) {
    return m.reply(
      `❌ Wrong format!\n\nUse: *${usedPrefix}${command} <SenderName> | <message>*\n\nExample:\n  ${usedPrefix}${command} Ahmed | Hello there!`
    )
  }

  const senderName = parts[0]
  const message    = parts.slice(1).join('|').trim() // allow | inside message

  await m.reply('🖼️ Generating your chat screenshot... Please wait!')

  // ── Optionally grab avatar from quoted image ──────────────────────────────
  let senderAvatar
  try {
    if (quoted?.msg?.mimetype?.startsWith('image')) {
      senderAvatar = await quoted.download()
    }
  } catch { /* ignore, avatar is optional */ }

  // ── Generate ──────────────────────────────────────────────────────────────
  const qwa = new Qwa()

  let result
  try {
    result = await qwa.generate({
      sender_name:   senderName,
      message,
      time:          new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: false }),
      ...(senderAvatar && { sender_avatar: senderAvatar }),
    })
  } catch (e) {
    return m.reply(`❌ Failed to generate image.\n\n_${e.message}_`)
  }

  if (!result?.buffer) {
    return m.reply('❌ The API returned an empty response. Please try again later.')
  }

  // ── Send result ───────────────────────────────────────────────────────────
  const caption = `🖼️  *Fake Chat Screenshot*\n\n👤  Sender  :  *${senderName}*\n💬  Message  :  ${message}`

  await conn.sendMessage(
    m.chat,
    { image: result.buffer, caption },
    { quoted: m }
  )
}

handler.help    = ['fakechat']
handler.command = /^(fakechat|fakem|qwa|chatfake)$/i
handler.tags    = ['tools']
handler.limit   = false
export default handler
